### ISSUE TITLE
Unable to locate a login form on: https:// ....

### ISSUE THREAD

**Issue by BesoBerlin** [Ethical-H4CK3R/AnyPhish#1]
i wasnt able to clone any site...

**Comment by Bitwise-01** [comment]
some sites use javascript and the script won't be able to locate the login form. It works on sites like facebook and github. Ex: 'python clone.py https://facebook.com/login.php', 'python clone.py https://github.com/login', 'python clone.py https://www.netflix.com/login'. If you're going to clone a site, it has to be the site's login page.
